from typing import Optional
from pathlib import Path
from abc import ABC, abstractmethod
from promptpy.utils import get_cache_tag, save, load, hash_str
from promptpy.message import Message

completion_cache_path = Path("completions")

class CompletionError(Exception):
    pass

class Model(ABC):
    """An abstract class for implementing LLMs."""

    @abstractmethod
    def get_completion(self, messages: list[Message], stop: Optional[str] = None) -> Optional[str]:
        """Takes a past conversation and a stop sequence, and returns a completion generated by the LLM
        or None.

        Args:
            messages: The past conversation.
            stop: Stop sequence for which the LLM should stop the completion.
        """
        
    @abstractmethod
    def __repr__(self) -> str:
        """Representation of the LLM and its configuration. Necessary for prompt caching."""
    
    def get_response(self, messages: list[Message], stop: Optional[str] = None) -> str:
        """Takes a past conversation and a stop sequence, and returns a completion generated by the LLM
        or raises a CompletionError if not possible. Valid completions are cached if the use_cache is True.

        Args:
            messages: The past conversation.
            stop: Stop sequence for which the LLM should stop the completion.
        """
        key = hash_str(repr([get_cache_tag(), self, messages]))
        file_path = completion_cache_path / key
        cached = load(file_path)
        if cached is not None:
            return cached
        completion = self.get_completion(messages, stop)
        if completion is None:
            raise CompletionError("Model was not able to create a valid completion.")
        save(file_path, completion)
        return completion
        
_model: Optional[Model] = None

def set_model(model: Model) -> None:
    """Set model to use for prompting."""
    global _model
    _model = model

def get_model() -> Model:
    assert _model is not None, "No model was set."
    return _model